import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Providers from "@/utils/query-client/query-client";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <title>Taroko Project</title>
      </head>

      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>
          {children}
          <ReactQueryDevtools initialIsOpen={false} />
          <ToastContainer autoClose={3000} />
        </Providers>
      </body>
    </html>
  );
}
